# Derive the book's version from git and write it where a render can read it.
#
# Runs before every render (`project: pre-render` in _quarto.yml). The version
# is never typed by hand: it is whatever the most recent `v*` tag says, and the
# way to change it is to tag a release (plans/versioning_and_feedback.md).
#
#   on a tag        v0.1.0            -> "0.1.0"           a released version
#   after a tag     v0.1.0-3-gabc1234 -> "0.1.0-dev+abc1234"  a development build
#   before any tag                    -> "0.0.0-dev+abc1234"
#
# Three files come out of this, all gitignored, all regenerated each render:
#   _variables.yml        {{< var version >}} and friends, for the HTML
#   styles/version.tex    \bookversion and \bookreleased, for the PDF footer
#   _version-bibtex.md    the BibTeX block on the Welcome page. Shortcodes are
#                         not expanded inside fenced code, so the numbers have
#                         to be written into it literally.

git <- function(...) {
  out <- suppressWarnings(system2("git", c(...), stdout = TRUE, stderr = FALSE))
  if (!is.null(attr(out, "status")) || length(out) == 0) return(NA_character_)
  out[1]
}

describe <- git("describe", "--tags", "--match", "v*", "--long")
commit   <- git("rev-parse", "--short=7", "HEAD")
if (is.na(commit)) commit <- "unknown"

if (is.na(describe)) {
  # No tag yet: everything is a development build of nothing in particular.
  tag <- "v0.0.0"; distance <- 1L
} else {
  # "v0.1.0-3-gabc1234" -> tag "v0.1.0", distance 3
  parts    <- regmatches(describe, regexec("^(v[0-9][^-]*)-([0-9]+)-g[0-9a-f]+$", describe))[[1]]
  tag      <- parts[2]
  distance <- as.integer(parts[3])
}

is_release <- distance == 0L
base       <- sub("^v", "", tag)
version    <- if (is_release) base else paste0(base, "-dev+", commit)

# A release is dated by its tag; a development build by its last commit.
released <- if (is_release) git("log", "-1", "--format=%cs", tag) else git("log", "-1", "--format=%cs")
if (is.na(released)) released <- format(Sys.Date())
year <- substr(released, 1, 4)

writeLines(c(
  "# Generated by tools/version.R on every render. Do not edit; tag a release instead.",
  sprintf('version: "%s"', version),
  sprintf('released: "%s"', released),
  sprintf('year: "%s"', year),
  sprintf('commit: "%s"', commit),
  sprintf('is_release: %s', tolower(is_release))
), "_variables.yml")

writeLines(c(
  "% Generated by tools/version.R on every render. Do not edit; tag a release instead.",
  sprintf("\\newcommand{\\bookversion}{%s}", version),
  sprintf("\\newcommand{\\bookreleased}{%s}", released)
), "styles/version.tex")

writeLines(c(
  "```bibtex",
  "@book{putz_linear_models,",
  "  author    = {Putz, Austin},",
  "  title     = {Linear Models in Animal Breeding: A Worked Approach},",
  sprintf("  year      = {%s},", year),
  sprintf("  version   = {%s},", version),
  "  url       = {https://austin-putz.github.io/linear-models-in-animal-breeding/},",
  sprintf("  note      = {Version %s, released %s}", version, released),
  "}",
  "```"
), "_version-bibtex.md")

cat(sprintf("book version %s (%s)\n", version, released))
